---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
type: kubernetes.io/basic-auth
metadata:
  name: git-https
  annotations:
    tekton.dev/git-0: https://github.com
spec:
  fromNamespace: tap-install
