apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  namespace: workload-corby
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/scanning: "true"
    app.kubernetes.io/part-of: dev-control-plane
spec:
  source:
    git:
      url: https://github.com/cpage-pivotal/Dev.Control.Plane
      ref:
        branch: main
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"

